jwt:
  signing-key: taocoupon
  expires-time: 7d
  buffer-time: 1d
  issuer: taocoupon
mysql:
  host: 127.0.0.1
  port: 3306
  database: one_coupon
  username: root
  password: taocoupon
  param: parseTime=True&loc=Local&timeout=10000ms
redis:
  addr: 127.0.0.1:6379
  password: taocoupon
  db: taocoupon